### ISSUE TITLE
12章: i32.storeの実装で未実装のstore.memoriesを参照している

### ISSUE THREAD

**Issue by kubo39** [skanehira/zenn-books#4]
12章のi32.storeの実装時にはまだ説明および実装がされてないexecution.storeが保持しているランタイム上のメモリ領域を参照しています。
i32.storeの実装時点ではコンパイルおよびテストが通らないため、12章の説明で補足するかi32.storeの実装を後ろにまわすなどしたほうがよいのではないかと思いました。

- 12章: [i32.storeの実装](https://zenn.dev/skanehira/books/writing-wasm-runtime-in-rust/viewer/12_build_runtime_additional_instruction#i32.store%E3%81%AE%E5%AE%9F%E8%A3%85)
- 13章: [Memory Sectionのデコード実装](https://zenn.dev/skanehira/books/writing-wasm-runtime-in-rust/viewer/13_build_runtime_initialize_memory#memory-section%E3%81%AE%E3%83%87%E3%82%B3%E3%83%BC%E3%83%89%E5%AE%9F%E8%A3%85) (store上でのMemoryの初期設定はデコード処理とは独立事象なので節を分離したほうがよいかもしれない)

**Comment by skanehira** [comment]
本当だ。。
ありがとうございます、修正します

**Comment by skanehira** [comment]
修正しました
ありがとうございます 🙏
